#pragma once

#include <QApplication>
#include <QMainWindow>
#include <QDialog>
#include <QMenu>
#include <QMenuBar>
#include <QSplashScreen>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsPixmapItem>
#include <QScrollBar>
#include <QScreen>
#include <QPropertyAnimation>
#include <QRect>
#include <QTimer>
#include <QSharedPointer>
#include <QPushButton>
#include <QLineEdit>
#include <QLabel>
#include <QRadioButton>
#include <QSoundEffect>
#include <QMediaPlayer>
#include <QAudioOutput>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlRecord>
#include <QVector>
#include <QRegularExpression>
